#!/bin/sh /etc/rc.common

START=60
USE_PROCD=1

EXTRA_COMMANDS="action"

start_service() {
	procd_open_instance
	procd_add_mdns "smb" "tcp" "445"
	procd_set_param nice 5
	procd_set_param command /usr/sbin/smbd -F
	procd_set_param respawn
	procd_close_instance

	procd_open_instance
	procd_set_param nice 5
	procd_set_param command /usr/sbin/nmbd -F
	procd_set_param respawn
	procd_close_instance
}

action() {
	case "$1" in
	set-passwd)
		[ -z "$2" ] && exit 1
		printf "%s\n%s\n" "$2" "$2" | smbpasswd -s -a extensions		
		exit 0
		;;
	*)
		exit 1
		;;
	esac
}
