#!/bin/sh

. /etc/ranga/pub.sh
. ${NSWA_PREFIX}/lib/auth.sh

auth || exit 3

case "$1" in
umount-mainfs)
	${NSWA_PREFIX}/libexec/aumount /mnt/main
	exit $?
	;;
mainfs-stat)
	egrep "^[^ ]+ /mnt/main " /proc/mounts > /dev/null 2>&1
	if [ "$?" = "0" ]; then
		echo 'MOUNTED'
		df /mnt/main/ | tail -1 | awk '{print $3 "," $4}'
	else
		echo "NOT-MOUNTED"
	fi
	;;
*)
	exit 1
	;;
esac

exit 0
